version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: ghi084572
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oradata:/opt/oracle/oradata

  app:
    build:
      context: .
    image: my-sqlapp:latest
    container_name: sqlapp
    ports:
      - "8080:8080"
      - "5005:5005" # Debugging Port
    depends_on:
      - oracle-db
    entrypoint: ["/bin/sh", "-c", "sleep 20 && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app/app.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/xe
      SPRING_DATASOURCE_USERNAME: C##JAN
      SPRING_DATASOURCE_PASSWORD: ghi084572

volumes:
  oradata:
